# Generated by Django 4.2.8 on 2023-12-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0002_farmtech_farmer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='viewpaassword',
            new_name='ViewPassword',
        ),
    ]
