# Generated by Django 4.2.8 on 2023-12-12 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0003_rename_viewpaassword_login_viewpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('quantity', models.IntegerField()),
                ('img', models.ImageField(upload_to='gallery')),
                ('price', models.IntegerField()),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('purpose', models.TextField()),
                ('amount', models.IntegerField()),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.farmer')),
                ('techid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.farmtech')),
            ],
        ),
    ]
