# Generated by Django 4.2.8 on 2023-12-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0004_products_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='img',
            field=models.ImageField(default=-2020, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
