# Generated by Django 4.2.8 on 2023-12-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0012_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=-2013),
            preserve_default=False,
        ),
    ]
