# Generated by Django 4.2.8 on 2023-12-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0016_bookvehiclerent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lands',
            name='status',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
