# Generated by Django 4.2.8 on 2023-12-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0018_booklandrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklandrent',
            name='status',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
    ]
