# Generated by Django 4.2.8 on 2023-12-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0019_booklandrent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookvehiclerent',
            name='Status',
            field=models.CharField(default='1', max_length=20, null=True),
        ),
    ]
