# Generated by Django 4.2.8 on 2023-12-20 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0021_rename_vid_booklandrent_lid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklandrent',
            name='lid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmerapp.lands'),
        ),
    ]
