# Generated by Django 4.2.8 on 2023-12-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0022_alter_booklandrent_lid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklandrent',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
