# Generated by Django 4.2.8 on 2023-12-20 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0024_alter_bookvehiclerent_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookvehiclerent',
            old_name='Status',
            new_name='status',
        ),
    ]
