# Generated by Django 4.2.8 on 2023-12-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0025_rename_status_bookvehiclerent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklandrent',
            name='status',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookvehiclerent',
            name='status',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
    ]
